// v10 tooltips + schedules + total
(function setToday(){ const d=document.getElementById('visit-date'); if(d&&!d.value){ d.value=new Date().toISOString().slice(0,10);} })();
(function regimenToggle(){ const p=document.getElementById('dt-primary'), b=document.getElementById('dt-booster'), s=document.querySelector('#dt-regimen .regimen-steps'); if(p&&b&&s){ const u=()=>{ s.textContent=p.checked?s.dataset.primary:s.dataset.booster; renderSummary(); }; p.addEventListener('change',u); b.addEventListener('change',u); u(); } })();
const priceMap={'dt-generic:primary':37,'dt-generic:booster':37,'dt-child:primary':37,'uni5:primary':632,'hexaxim:primary':1450,'boostagen:booster':644,'boostrix:booster':582,'tig:single':747};
const unitMap={'tig:single':'บาท/โดส'};
const schedules={'dt-generic:primary':[0,1,7],'dt-generic:booster':[0,120],'dt-child:primary':[0,1,7],'uni5:primary':[0,2,4],'hexaxim:primary':[0,2,4],'boostagen:booster':[0,120],'boostrix:booster':[0,120],'tig:single':[0]};
const courseDoseCount={'dt-generic:primary':3,'dt-generic:booster':1,'dt-child:primary':3,'uni5:primary':3,'hexaxim:primary':3,'boostagen:booster':1,'boostrix:booster':1};
const labels={'dt-generic:primary':'DT Vaccine • Primary','dt-generic:booster':'DT Vaccine • Booster','dt-child:primary':'DT (เด็ก)','uni5:primary':'Uni5 (Pentavalent)','hexaxim:primary':'Hexaxim (Hexavalent)','boostagen:booster':'Boostagen Tdap','boostrix:booster':'Boostrix','tig:single':'Tetagam (HTIG)'};
function addMonths(d,m){const x=new Date(d),day=x.getDate();x.setMonth(x.getMonth()+m);if(x.getDate()!==day)x.setDate(0);return x}
function fmt(d){return d.toLocaleDateString('th-TH',{year:'numeric',month:'short',day:'numeric'})}
function getVisitDate(){const v=document.getElementById('visit-date').value;const d=v?new Date(v):new Date();return isNaN(d.getTime())?new Date():d}
function currentSelections(){const L=[]; const dtP=document.getElementById('dt-primary')?.checked; if(document.getElementById('dt-add')?.checked)L.push('dt-generic:'+(dtP?'primary':'booster')); if(document.getElementById('kid-add')?.checked)L.push('dt-child:primary'); if(document.getElementById('uni5-add')?.checked)L.push('uni5:primary'); if(document.getElementById('hexaxim-add')?.checked)L.push('hexaxim:primary'); if(document.getElementById('boostagen-add')?.checked)L.push('boostagen:booster'); if(document.getElementById('boostrix-add')?.checked)L.push('boostrix:booster'); if(document.getElementById('tig-add')?.checked)L.push('tig:single'); return L}
function renderSummary(){const sel=currentSelections(),list=document.getElementById('sum-list'),empty=document.getElementById('sum-empty'),total=document.getElementById('sum-total'); list.innerHTML=''; if(sel.length===0){empty.style.display='block'; total.textContent='รวมคอร์สวัคซีน: 0 บาท'; return;} empty.style.display='none'; const visit=getVisitDate(); let sum=0; sel.forEach(key=>{const months=schedules[key]||[0]; const lines=months.map((m,i)=>`เข็ม ${i+1}: ${fmt(addMonths(visit,m))}`); const unit=unitMap[key]||'บาท/เข็ม'; const price=priceMap[key]; const priceTxt=(price||price===0)? `${price.toLocaleString('th-TH')} ${unit}`:`<span class="muted">ราคา: —</span>`; const li=document.createElement('li'); li.innerHTML=`<b>${labels[key]||key}</b> — ${priceTxt}<br><span class="dose-lines">${lines.join('<br>')}</span>`; list.appendChild(li); if(key in courseDoseCount) sum += (price||0)*(courseDoseCount[key]||0); }); total.textContent='รวมคอร์สวัคซีน: '+sum.toLocaleString('th-TH')+' บาท';}
(function tooltips(){ function closeAll(){document.querySelectorAll('.tooltip.open').forEach(t=>t.classList.remove('open'));} document.addEventListener('click',e=>{const b=e.target.closest('.tip'); if(b){const id=b.getAttribute('data-tip'); const t=id&&document.getElementById(id); if(t){const was=t.classList.contains('open'); closeAll(); if(!was)t.classList.add('open');} return;} if(!e.target.closest('.tooltip')) closeAll(); }); })();
(function init(){document.getElementById('visit-date')?.addEventListener('change',renderSummary); ['dt-add','kid-add','uni5-add','hexaxim-add','boostagen-add','boostrix-add','tig-add'].forEach(id=>{const el=document.getElementById(id); if(el) el.addEventListener('change',renderSummary);}); renderSummary();})();
